### ISSUE TITLE
Add unit tests covering Marketo operator field changes

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#30]
## What / Why
Although not necessary to exercise every operator in tests (this should be covered by run-crank/typescript-cog-utilities#5), we should at least cover a few new branches of code and ensure the field is set correctly

## Scope / UAT Target
- [x] Add operator field assertion in "expected step fields" test for Marketo Lead Check Step
  - [x] Field is set with expected key
  - [x] Field is set to optional
- [x] Add error outcome assertion when `util.compare` throws UnknownOperatorError for Marketo Lead Check Step
- [x] Add error outcome assertion when `util.compare` throws InvalidOperandError for Marketo Lead Check Step

**Comment by amcpanaligan** [comment]
This was tested before by @saludangelito a month ago. References are below. Also, I ran the test locally and everything was covered

**Expected Fields:** https://github.com/run-crank/cog-marketo/blob/master/test/steps/lead-field-equals.ts#L52
**Operators and Operands:**

https://github.com/run-crank/cog-marketo/blob/master/test/steps/lead-field-equals.ts#L367
https://github.com/run-crank/cog-marketo/blob/master/test/steps/lead-field-equals.ts#L345
