### ISSUE TITLE
Add Structured Data Records to Appropriate Steps

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#51]
## What / Why
In order to help users diagnose failed test scenarios, we should add structured step response data that helps "show" the underlying information used in the step.

## Scope / UAT Target
- [x] Step Updates (see [this example from the Pardot Cog](https://github.com/run-crank/cog-pardot/commit/5208f7b6a43cc6b27be3afbefae70ec1d9935ef8)):
  - [x] `LeadFieldEqualsStep`: In any outcome where a lead was found (whether or not the step passes/fails/errors), the lead object (`data.result[0]`) should be returned as a Key/Value response record.  Its `id` should be `lead` and name should be `Checked Lead`
  - [x] `CustomObjectFieldEqualsStep`
    - [x] If more than one matching custom object was found, a list of matching custom object records should be returned as a Table response record. Its `id` should be `matchedObjects` and `name` should be `Matched ${customObjectLabelPlural}`
    - [x] If a single matching custom object was found, regardless of pass/fail, the custom object record should be returned as a Key/Value response record. Its `id` should be `customObject` and name should be `Checked ${customObjectLabelPlural}`
  - [x] `CheckLeadActivityStep`: In any outcome where activities were found (whether or not any of them were successfully validated), a list of those activities should be returned as a table response record. Its `id` should be `matchedActivities` and `name` should be `Matched ${activityLabel} Records`
  - [x] `AddLeadToSmartCampaignStep`
    - [x] In any outcome where a lead was found (regardless of outcome) for the given email address, a Key/Value response record should be returned with the lead record as data. Its `id` should be `lead` and its `name` should be `Lead To Be Added`
    - [x] In any outcome where a campaign was found (regardless of outcome), the campaign object should be returned as a Key/Value response. Its `id` should be `campaign` and its `name` should be `Smart Campaign`

## Proposed Resolution
- [x] Update the Cog protobuf definition and built files
  - [x] The `cog.proto` should be updated to [the version released in Crank v0.9.0](https://github.com/run-crank/cli/blob/v0.9.0/src/assets/proto/cog.proto)
  - [x] The Cog protobuffer and gRPC protobuffer scripts (and typings) should be updated to [the versions released in Crank v0.9.0](https://github.com/run-crank/cli/tree/v0.9.0/src/proto)
- [x] Update core cog classes/interfaces (see [this example from the Pardot Cog](https://github.com/run-crank/cog-pardot/commit/088a5d92f67139357ce02cd6d97daae33a4e126c))
  - [x] There should be three new protected methods on the BaseStep class, which return the three types of structured data records:
    - [x] For objects: `keyValue(id: string, name: string, data: Record<string, any>): StepRecord {}`
    - [x] For arrays of objects: `table(id: string, name: string, headers: Record<string, string>, rows: Record<string, any>[]): StepRecord {}`
    - [x] For binary data: `binary(id: string, name: string, mimeType: string, data: string | Uint8Array): StepRecord {}`
  - [x] The `pass`, `fail`, and `error` methods should be updated to take a third, optional argument of type `StepRecord[]`, which should be added to the response.
  - [x] ExpectedRecord handling:
    - [x] There should be a new `ExpectedRecord` interface exported in `base-step.ts` (see linked Pardot example commit above)
    - [x] There should be a new, optional expectedRecords protected property on the `BaseStep` class
    - [x] The `BaseStep::getDefinition()` method should set any expected records if provided on the protected property by an implementing step class.

**Comment by amcpanaligan** [comment]
@iamEAP for `CheckLeadActivityStep`, I am quite confused on how we can make `name` as dynamic. Unless it pertains to the `name` of the activity in the table's rows/records
