### ISSUE TITLE
Check a Marketo Lead's activity step fails when adding field that is not really an attribute

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-marketo#67]
When I used a field that is not really an attribute, my test is failing. However, these non-attribute fields can be seen on the structured data records. So there's a chance a user might think that it can also be used to check the activity

## Repro Steps:
1. Run "**Check a Marketo Lead's Activity**" step.
     - The activity type ID (number) or name: New Lead
     - The number of minutes prior to now to use when filtering the activity feed: 30
     - Add withAttributes fields? Yes
     - withAttributes object key: campaignId
     - withAttributes object value 1032

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/75956144-3b682900-5ef2-11ea-917d-45fdfa5f98c1.png)

## Expected Result:
Non-attribute fields can be removed from the structured data records or those fields can be checked.

**Comment by amcpanaligan** [comment]
Waiting for @iamEAP go signal
